project: sensingclues-ndvi

aois:
  Zambia:
    path: C:\Users\20244650\Documents\GitHub\environmental-time-series\app\www\data\AoI\AoI_Zambia_By_Life_Connected.geojson
  Zambia_Mponda:
    path: C:\Users\20244650\Documents\GitHub\environmental-time-series\app\www\data\AoI\AoI_Zambia_Mponda_By_Life_Connected.geojson

sensors:
  sentinel2:
    collection: COPERNICUS/S2_SR_HARMONIZED
    resolutions: [100, 1000]
    start_date: '2017-03-01'

legacy_data_root: C:\Users\20244650\Documents\GitHub\environmental-time-series\app\www\data\NDVI

output_root: outputs
