project: sensingclues-ndvi

aois:
  Zambia:
    path: C:\Users\20244650\Documents\GitHub\environmental-time-series\app\www\data\AoI\AoI_Zambia_By_Life_Connected.geojson
  Zambia_Mponda:
    path: C:\Users\20244650\Documents\GitHub\environmental-time-series\app\www\data\AoI\AoI_Zambia_Mponda_By_Life_Connected.geojson
  Zambia_WL:
    path: C:\Users\20244650\Documents\GitHub\environmental-time-series\app\www\data\AoI\AoI_Zambia_WL.geojson

sensors:
  sentinel2:
    collection: COPERNICUS/S2_SR_HARMONIZED
    resolutions: [100, 1000]
    start_date: '2017-03-01'
  modis:
    resolutions:
      250:
        collection: MODIS/061/MOD13Q1
      500:
        collection: MODIS/061/MOD13A1
      1000:
        collection: MODIS/061/MOD13A2
  burned_area:
    collection: MODIS/061/MCD64A1
    band: BurnDate
    resolutions: [500]

legacy_data_root: C:\Users\20244650\Documents\GitHub\environmental-time-series\app\www\data\NDVI
legacy_burned_area_root: C:\Users\20244650\Documents\GitHub\environmental-time-series\app\www\data\BurnedArea

output_root: outputs
